CREATE SCHEMA IF NOT EXISTS sm;

-- -----------------------------------------------------
-- Все зарегистрированные пользователи
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sm.people
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    varchar(50) NOT NULL UNIQUE,
    email       varchar(50) NOT NULL UNIQUE,
    password    varchar(64) NOT NULL,
    role        varchar(50) NOT NULL,
    created_at  timestamp   NOT NULL,
    disabled_at timestamp   NULL
);

-- -----------------------------------------------------
-- Все поcты пользователей
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sm.posts
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id     int REFERENCES sm.people (id) ON DELETE CASCADE,
    image_link  varchar,
    text        varchar   NOT NULL,
    created_at  timestamp NOT NULL,
    updated_at  timestamp NOT NULL,
    disabled_at timestamp NULL
);